### ISSUE TITLE
Security levels in the attestation

### ISSUE THREAD

**Issue by fmarino-ipzs** [oauth-wg/draft-ietf-oauth-attestation-based-client-auth#15]
Since the EUDI Wallet instance may have different level of security depending on its own hardware and/or software capabilities, here the proposal: define a claim name for exposing different level of security of the wallet instance.

Example:"gold", "silver" and "bronze" or "high", "medium", "low" depending on the framework used. 

This proposal enables the security evaluation to the credential issuing side (or any other Relying Party) without knowing any specific hardware or software features (e.g. OS, etc.).

**Comment by paulbastian** [comment]
The RFC may be used to issue wallet attestations in the eIDAS use case, giving additional information on the key type of the `cnf` and the user authenticaiton mechanisms, see more info [here](https://www.linkedin.com/feed/update/urn:li:activity:7056179875635724289/). A Wallet alone does not achieve a LoA but only supports the issuer in achieving an LoA for the lifecycle of an issues credential. However, a claim `supported_LoA` could be useable

**Comment by peppelinux** [comment]
Here the proposal raised in the italian implementation

`asc_values_supported` and `asc`

where ASC is the acronym of Attested Security Context

this aims do disambiguate the meaning of LoA, that is referred to person identities, to the scope of this attestation, that's entirely related to the security context of a personal device

**Comment by peppelinux** [comment]
the parameter name was renamed to `attested_security_context` (ASC) and we read it here:
https://github.com/vcstuff/draft-looker-oauth-attestation-based-client-auth/blob/main/draft-looker-oauth-attestation-based-client-auth.md#wallet-instance-attestation

In that form **it is just a non-normative example, so some explanatory/normative text is needed**.

ASC aims to introduce a classification for the common capabilities of the device/mobile-app and a simple evaluation by the issuers.

Generally, it

- avoids that the issuers should take any responsability by attesting `key_type` and `user_authentication`, since the sole responsability of the wallet security compliance is the wallet provider

- avoids the implicit disclosure of system internals or mobile os name/brand. These could be derived by knowing the `key_type`, since there are some technologies that are only available on some specific platforms/os/versions. Then it improves the privacy, because the issuer cannot know which mobile os the user prefers or simply uses.

-  requires a common framework where different device capabilities and user auth method must be mapped, classified and grouped in the ASC levels. A matrix with the key_types and user_auth values, grouped by each ASC level, is then required (but outside of the scope of this specs). 

- avoids that future features that today still don't exist, for example `key_type: "super-Strong-box-3.0"`, don't introduce anything more to the issuers that just need to know which are the ASC level and the one carried in the WIA, without any details (madated to a common framework)

example of how the ACS levels could be defines can be found in literature as they was for ACR and AMR

**Comment by paulbastian** [comment]
While I agree that ASC is a good idea, the argument for privacy is negligible as every browser user sends the OS information anyway, additional information of the key type is very small

**Comment by tplooker** [comment]
Related to #29

**Comment by paulbastian** [comment]
Solved in #48

**Comment by c2bo** [comment]
I think we can close this?

**Comment by paulbastian** [comment]
key attestations and associated parameters will be handled separately in [OpenID4VCI](https://github.com/openid/OpenID4VCI/pull/389)
